name: hagital-ci

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say hello
        run: |
          echo "Hello from hagital! Live Troubleshooting Script"
          echo "Aye mi o"
          echo "Wetin be this"
